### PR TITLE
added "--latest" to build docker image

### PR DESCRIPTION
**Pull request by hiltonlima**
By adding the `--latest` parameter the `.sha_information` file is filled correctly.

Issue: https://github.com/project-chip/certification-tool/issues/98

### CODE REVIEW

**Review by rquidute — APPROVED** [review]

**Review by antonio-amjr — APPROVED** [review]

**Comment by mikaelhm** [comment]
Actually, with public images, I don't think we should have `build.sh` in `auto-install.sh`.

What do you think?

**Comment by hiltonlima** [comment]
> Actually, with public images, I don't think we should have `build.sh` in `auto-install.sh`.
> 
> What do you think?

Good morning Mikael,

I partially agree. We currently have the structure to use public Docker images. However, we don't actually have this working, as the images are not on any server, right?

What I thought here is that we could remove the build from the auto-install images and call the build script separately. Thinking about a clean installation... Maybe we need to divide the auto-install into two parts? Prerequisites and then updating the sampleapps (SDK)?

**Comment by fabiowmm** [comment]
> > Actually, with public images, I don't think we should have `build.sh` in `auto-install.sh`.
> > What do you think?
> 
> Good morning @mikaelhm,
> 
> I partially agree. We currently have the structure to use public Docker images. However, we don't actually have this working, as the images are not on any server, right?
> 
> What I thought here is that we could remove the build from the auto-install images and call the build script separately. Thinking about a clean installation... Maybe we need to divide the auto-install into two parts? Prerequisites and then updating the sampleapps (SDK)?

Actually this separation will be needed anyway to modularize TH for supporting different test programs. Some of the prereqs as well as the sample apps need to move out of the core and into the Matter Program (matter collection).

**Comment by mikaelhm** [comment]
Apollogies for the delay @hiltonlima. 

The docker images are already public, and we should have user use those.
https://github.com/orgs/project-chip/packages?tab=packages&q=cert

By default on the main brach, we can have the `docker-compose.yml` point to `latest` version of the image, but for releases we can lock it down to a specific version of the image.

**Comment by hiltonlima** [comment]
This PR is not needed anymore

**Pull request closed without merging**
